version: 0.2

phases:
  pre_build:
    commands:
      - echo "Initializing Terraform..."
      - terraform init
  build:
    commands:
      - echo "Applying Terraform plan..."
      - terraform apply -auto-approve
artifacts:
  files:
    - '**/*'
